#!/bin/bash

set -e

install_ll() {
    ./xbuild/ruby-install $SPEC

    for gemfile in "$ETC/Gemfile" "$ETC/Gemfile.$( basename $LOCATION )"; do
        test -f $gemfile || continue
        BUNDLE_GEMFILE=$gemfile PATH="$LOCATION/bin:$PATH" bundle install
    done
}

cd $(dirname $0)
source ./functions
install_or_update_xbuild
install_versions
