#!/bin/bash
# kuroda

set -e

cd $( dirname $0 )

sync_config=/etc/anybuild/sync-lang
test -f $sync_config && source $sync_config

if [ -n "$server" ]; then
    echo "$server からビルド済みデータを取得..."
    ./sync-lang --pull --delete
fi

if [ ! -d ./xbuild ]; then
    git clone https://github.com/tagomoris/xbuild.git xbuild
fi

for installer in $( ls any-*-install ); do
    ./$installer
done

if [ -n "$server" ]; then
    echo "ビルドしたものを $server に同期..."
    ./sync-lang --push
fi
