#!/bin/bash
#
#  - versions.txt からインストールするバージョンとインストールパスを読んでxbuildでインストール
#  - Gemfileがあれば、各rubyにbundlerでモジュールインストール

set -e

cd $( dirname $0 )

etc=/etc/anybuild/ruby
versions=$etc/versions.txt
env=$etc/env

export MAKEFLAGS="-j $( getconf _NPROCESSORS_ONLN )"
test -f $env && source $env

test -f $versions || exit 0

while read spec; do
    set $(echo $spec)
    version=$1
    location=$2

    # build ruby
    mkdir -p "$location"
    ./xbuild/ruby-install $spec

    # install modules
    for gemfile in "$etc/Gemfile" "$etc/Gemfile.$( basename $location )"; do
        test -f $gemfile || continue
        BUNDLE_GEMFILE=$gemfile PATH="$location/bin:$PATH" bundle install
    done
done < $versions
