#!/bin/bash
# hiroya
#
#  - versions.txt からインストールするバージョンとインストールパスを読んでxbuildでインストール
#  - サービス独自のカスタム definitions は PHP_BUILD_DEFINITION_PATH に置いておく

set -x
set -e

cd $( dirname $0 )

etc=/etc/anybuild/php
versions=$etc/versions.txt
export PHP_BUILD_DEFINITION_PATH=$etc/definitions/

export LDFLAGS="-L/usr/lib64/mysql"
export MAKEFLAGS="-j $( getconf _NPROCESSORS_ONLN )"

test -f $versions || exit

while read spec; do
    set $(echo $spec)
    version=$1
    location=$2

    # build php
    if [ ! -x "$location/bin/php" ]; then
        mkdir -p "$location"
        ./xbuild/php-install $spec
    fi

    # install pear modules
    # pearfile なんてものは無いけど、perl の cpanfile の扱いと揃えておく
    for pearfile in "$etc/pearfile" "$etc/pearfile.$( basename $location )"; do
        test -f "$pearfile" || continue
        for module in $( grep -v '#' $pearfile ); do
            $location/bin/pear list $module 1>/dev/null || sudo $location/bin/pear install $module
        done
    done

    # install pecl modules
    for peclfile in "./peclfile" "./peclfile.$( basename $location )"; do
        test -f "$peclfile" || continue
        for module in $( grep -v '#' $peclfile ); do
            $location/bin/pecl list $module 1>/dev/null || sudo $location/bin/pecl install $module
        done
    done
done < $versions
