#!/bin/bash

set -e

install_ll() {
    ./xbuild/perl-install $SPEC
    # cpanm v1.70はcpanfileの指定がまだできない。githubから開発版をもってくる。
    PATH="$LOCATION/bin:$PATH" cpanm --notest http://github.com/miyagawa/cpanminus/tarball/1.7102

    # install modules
    for cpanfile in "$ETC/cpanfile" "$ETC/cpanfile.$( basename $LOCATION )"; do
        test -f "$cpanfile" || continue
        PATH="$LOCATION/bin:$PATH" cpanm --notest --cpanfile "$cpanfile" --installdeps ./
    done
}

cd $(dirname $0)
source ./functions
install_or_update_xbuild
install_versions
