#!/bin/bash

set -e

install_ll() {
    ./xbuild/python-install $SPEC

    for pipfile in "$ETC/pipfile" "$ETC/pipfile.$( basename $LOCATION )"; do
        test -f $pipfile || continue
        PATH="$LOCATION/bin:$PATH" pip install -r $pipfile
    done
}

cd $(dirname $0)
source ./functions
install_or_update_xbuild
install_versions
