#!/bin/bash
# kuroda
#
#  - versions.txt からインストールするバージョンとインストールパスを読んでxbuildでインストール
#  - cpanfileがあれば、各perlにcpanmでモジュールをインストール
#  - cpanfile.<インストールパスのdir名>があればそれも追加でインストール

set -x
set -e

cd $( dirname $0 )

etc=/etc/anybuild/perl
versions=$etc/versions.txt

export MAKEFLAGS="-j $( getconf _NPROCESSORS_ONLN )"

test -f $versions || exit

while read spec; do
    set $(echo $spec)
    version=$1
    location=$2

    # build perl
    if $location/bin/perl --version 2> /dev/null | grep -q "v${version}"; then
        echo "perl-$version on $location is already installed."
    else
        mkdir -p "$location"
        ./xbuild/perl-install $spec
        # cpanm v1.70はcpanfileの指定がまだできない。githubから開発版をもってくる。
        PATH="$location/bin:$PATH" cpanm --notest http://github.com/miyagawa/cpanminus/tarball/1.7102
    fi

    # install modules
    for cpanfile in "$etc/cpanfile" "$etc/cpanfile.$( basename $location )"; do
        test -f "$cpanfile" || continue
        PATH="$location/bin:$PATH" cpanm --notest --cpanfile "$cpanfile" --installdeps ./
    done
done < $versions
