#!/bin/bash
# hiroya
#
#  - versions.txt からインストールするバージョンとインストールパスを読んでxbuildでインストール
#  - サービス独自のカスタム definitions は PHP_BUILD_DEFINITION_PATH に置いておく

set -e

cd $( dirname $0 )

etc=/etc/anybuild/php
versions=$etc/versions.txt
export PHP_BUILD_DEFINITION_PATH=$etc/definitions/

export LDFLAGS="-L/usr/lib64/mysql"
export MAKEFLAGS="-j $( getconf _NPROCESSORS_ONLN )"

test -f $versions || exit 0

while read spec; do
    set $(echo $spec)
    version=$1
    location=$2

    # default definitionを使わず、
    # /etc/anybuild/php/definitions/<php_version>-<release_name>
    # で管理するの仕様にしているので、-*を取り除いてバージョンチェックする。
    expected_version=${version%%-*}

    # build php
    if $location/bin/php --version 2> /dev/null | grep -q "PHP $expected_version "; then
        echo "php $version is already installed on $location"
    else
        mkdir -p "$location"
        ./xbuild/php-install $spec
    fi

    # install pear modules
    # pearfile なんてものは無いけど、perl の cpanfile の扱いと揃えておく
    for pearfile in "$etc/pearfile" "$etc/pearfile.$( basename $location )"; do
        test -f "$pearfile" || continue
        for module in $( grep -v '#' $pearfile ); do
            $location/bin/pear list $module 1>/dev/null || sudo $location/bin/pear install $module
        done
    done

    # install pecl modules
    for peclfile in "./peclfile" "./peclfile.$( basename $location )"; do
        test -f "$peclfile" || continue
        for module in $( grep -v '#' $peclfile ); do
            $location/bin/pecl list $module 1>/dev/null || sudo $location/bin/pecl install $module
        done
    done
done < $versions
