#!/bin/bash

set -e

sync_config=/etc/anybuild/sync-lang

cd $(dirname $0)

test -f $sync_config && source $sync_config

if [ -n "$SERVER" ]; then
    echo "Pulling built lang from ${SERVER}..."
    ./sync-lang pull --delete
fi

for installer in $( ls any-*-install ); do
    ./$installer
done

if [ -n "$SERVER" ]; then
    echo "Pushing incremental built lang to ${SERVER}..."
    ./sync-lang push
fi
