#!/bin/bash

set -e

install_ll() {
    export PHP_BUILD_DEFINITION_PATH=$ETC/definitions/

    # default definitionを使わず、
    # /etc/anybuild/php/definitions/<php_version>-<release_name>
    # で管理するの仕様にしているので、-*を取り除いてバージョンチェックする。
    local expected_version=${TARGET_VERSION%%-*}

    if $LOCATION/bin/php --version 2> /dev/null | grep -q "PHP $expected_version "; then
        echo "php $TARGET_VERSION is already installed on $LOCATION"
    else
        ./xbuild/php-install $SPEC
    fi

    # install pear modules
    # pearfile なんてものは無いけど、perl の cpanfile の扱いと揃えておく
    for pearfile in "$ETC/pearfile" "$ETC/pearfile.$( basename $LOCATION )"; do
        test -f "$pearfile" || continue
        for module in $( grep -v '#' $pearfile ); do
            $LOCATION/bin/pear list $module 1>/dev/null || sudo $LOCATION/bin/pear install $module
        done
    done

    # install pecl modules
    for peclfile in "./peclfile" "./peclfile.$( basename $LOCATION )"; do
        test -f "$peclfile" || continue
        for module in $( grep -v '#' $peclfile ); do
            $LOCATION/bin/pecl list $module 1>/dev/null || sudo $LOCATION/bin/pecl install $module
        done
    done
}

cd $(dirname $0)
source ./functions
install_or_update_xbuild
install_versions




