#!/bin/bash
# kuroda

set -e

usage() {
    (
      echo "Usage:"
      echo "    sync-lang --check [lang_name[/version]]"
      echo "    sync-lang --pull|--push [--dry-run] [lang_name[/version]] "
      echo ""
      echo "Requires:"
      echo "    /etc/anybuild/sync-lang"
      echo "    # e.g."
      echo "    # role=app"
      echo "    # server=rsync.mydain.com"
    ) 1>&2
    exit 1
}


sync_config=/etc/anybuild/sync-lang

# require role, server
source $sync_config

if [  -z "$server" -o  -z "$role" ]; then
    echo 'No (lang)server or role specified.' 1>&2
    exit 1
fi

rsyncd_ro_module='lang_ro'
rsyncd_rw_module='lang_rw'

arch=$( facter architecture )
os=$( facter operatingsystem )
release=$( facter operatingsystemrelease )
release=${release%.?}

local_path='/usr/local/lang'
remote_path="/$role/$os/$release/$arch"

# Options
GETOPT=$(getopt -o h,d --long check,pull,push,dry-run,delete -- "$@")
[ $? != 0 ] && usage
eval set -- "$GETOPT"

while true
do
  case $1 in
  --check)
      opt_check=1
      shift
      ;;
  --pull)
      opt_pull=1
      shift
      ;;
  --push)
      opt_push=1
      shift
      ;;
  --dry-run | -d)
      opt_dryrun=1
      shift
      ;;
  --delete )
      opt_delete=1
      shift
      ;;
  -h)
      usage
      ;;
  --)
      shift
      break
      ;;
  *)
      usage
      ;;
  esac
done

if [ -n "$1" -a "$1" != "/" ]; then
  local_path="$local_path/$1"
  remote_path="$remote_path/$1"
fi

if [ -n "$opt_check" ]; then
  # 差分が無無いときのみ0で終了
  stats=$(
    rsync -avc --delete --dry-run --max-delete 1 --stats \
      "${server}::${rsyncd_ro_module}${remote_path}/" \
      "$local_path/" |
      awk '/^(deleting|Number of files transferred:)/'
  )

  test -z "$stats" && exit 2

  echo "$stats" | grep -q 'deleting' && exit 1

  diff_cnt=$( echo $stats | awk '/Number of files transferred:/{ print $NF }' )

  if [ $diff_cnt -eq 0 ]; then
      exit 0
  else
      exit 1
  fi
fi

rsync_opts='-avc'
test -n "$opt_dryrun" && rsync_opts="$rsync_opts --dry-run"
test -n "$opt_delete" && rsync_opts="$rsync_opts --delete"

if [ -n "$opt_pull" ]; then
  set -x
  mkdir -p "$local_path"
  rsync $rsync_opts "${server}::${rsyncd_ro_module}${remote_path}/" "$local_path/"
fi

if [ -n "$opt_push" ]; then
  set -x
  rsync $rsync_opts "$local_path/" "${server}::${rsyncd_rw_module}${remote_path}/"
fi


